# See https://github.com/pages-themes/slate#usage
remote_theme: pages-themes/slate@v0.2.0
plugins:
- jekyll-remote-theme


# See https://github.com/pages-themes/slate#configuration-variables
title: "TeX Hour"
description: "A weekly video meeting"
show_downloads: false

permalink: /:categories/:year/:month/:day/:title/

# Fix: GitHub Metadata: No GitHub API authentication could be found. [..]
# "No GitHub API authentication"
# https://github.com/github/pages-gem/issues/399

github: [metadata]

# https://seankilleen.com/2020/02/how-to-deploy-github-pages-on-a-schedule-to-publish-future-posts/
future: true

# Perhaps useful for page fragments.
# https://remarkablemark.org/blog/2020/04/04/jekyll-heading-anchor-links/
