# See https://github.com/pages-themes/slate#usage
remote_theme: pages-themes/slate@v0.2.0
plugins:
- jekyll-remote-theme


# See https://github.com/pages-themes/slate#configuration-variables
title: "TeX Hour"
description: "A weekly video meeting"
show_downloads: false

permalink: /:categories/:year/:month/:day/:title/

# Perhaps useful for page fragments.
# https://remarkablemark.org/blog/2020/04/04/jekyll-heading-anchor-links/
